# Generated by Django 5.2.1 on 2025-05-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='api_key_salt',
            field=models.CharField(default='b8f63eecde4f470b', editable=False, max_length=16),
        ),
    ]
