# Generated by Django 5.2.1 on 2025-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_organization_api_key_salt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="api_key_salt",
            field=models.CharField(
                default="39bbd4db64c24eae", editable=False, max_length=16
            ),
        ),
    ]
