# Generated by Django 5.2.1 on 2025-05-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_organization_api_key_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='api_key_salt',
            field=models.CharField(default='806f1dce59ff4580', editable=False, max_length=16),
        ),
    ]
