# Generated by Django 5.2.1 on 2025-05-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_organization_api_key_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='api_key_salt',
            field=models.CharField(default='0d3363cff48d4d98', editable=False, max_length=16),
        ),
    ]
