# Generated by Django 5.2.1 on 2025-05-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_organization_api_key_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='api_key_salt',
            field=models.CharField(default='f00ec487393e475b', editable=False, max_length=16),
        ),
    ]
