# Generated by Django 5.2.1 on 2025-05-26 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='database',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='report_management.database'),
        ),
        migrations.AlterField(
            model_name='query',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='report_management.node'),
        ),
    ]
