# Generated by Django 5.2.1 on 2025-05-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
