# Generated by Django 5.2.1 on 2025-05-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_management', '0002_node_database_alter_query_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='database',
        ),
    ]
