# Generated by Django 5.2.1 on 2025-05-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_management', '0003_alter_node_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
