name: Report Management(Development)

on:
  push:
    branches:
      - dev

env:
  DOCKER_IMAGE: 923083696216.dkr.ecr.us-east-1.amazonaws.com/report-management-service
  ECR_REGISTRY: 923083696216.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ECR
        id: ecr
        uses: jwalton/gh-ecr-login@v3
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_IMAGE:${{ github.run_number }} .

      - name: Tag and Push to ECR
        run: |
          docker tag 923083696216.dkr.ecr.us-east-1.amazonaws.com/report-management-service:${{ github.run_number }} $DOCKER_IMAGE:latest
          docker push 923083696216.dkr.ecr.us-east-1.amazonaws.com/report-management-service:${{ github.run_number }}
          docker push 923083696216.dkr.ecr.us-east-1.amazonaws.com/report-management-service:latest

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy on EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 923083696216.dkr.ecr.us-east-1.amazonaws.com
            
            # Stop and remove existing containers
            docker rm -f report-backend report-db || true
            
            # Create a Docker network for the containers to communicate
            docker network create report-network || true
            
            # Start the database container
            docker run -d \
              --name report-db \
              --network report-network \
              -e POSTGRES_DB=${{ secrets.DB_NAME }} \
              -e POSTGRES_USER=${{ secrets.DB_USERNAME }} \
              -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -v postgres_data:/var/lib/postgresql/data/ \
              -p 1433:5432 \
              postgres:15

            # Pull the latest image
            docker pull 923083696216.dkr.ecr.us-east-1.amazonaws.com/report-management-service:${{ github.run_number }}
            
            # Run makemigrations
            docker run --rm \
              --network report-network \
              -e DEBUG=${{ secrets.DEBUG }} \
              -e DJANGO_DB_HOST=report-db \
              -e DJANGO_DB_NAME=${{ secrets.DB_NAME }} \
              -e DJANGO_DB_USER=${{ secrets.DB_USERNAME }} \
              -e DJANGO_DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              923083696216.dkr.ecr.us-east-1.amazonaws.com/report-management-service:${{ github.run_number }} \
              python manage.py makemigrations

            # Run migrations
            docker run --rm \
              --network report-network \
              -e DEBUG=${{ secrets.DEBUG }} \
              -e DJANGO_DB_HOST=report-db \
              -e DJANGO_DB_NAME=${{ secrets.DB_NAME }} \
              -e DJANGO_DB_USER=${{ secrets.DB_USERNAME }} \
              -e DJANGO_DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              923083696216.dkr.ecr.us-east-1.amazonaws.com/report-management-service:${{ github.run_number }} \
              python manage.py migrate

            # Start the application container
            docker run -d \
              --name report-backend \
              --network report-network \
              -p 3493:3493 \
              -e DEBUG=${{ secrets.DEBUG }} \
              -e DJANGO_DB_HOST=report-db \
              -e DJANGO_DB_NAME=${{ secrets.DB_NAME }} \
              -e DJANGO_DB_USER=${{ secrets.DB_USERNAME }} \
              -e DJANGO_DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              923083696216.dkr.ecr.us-east-1.amazonaws.com/report-management-service:${{ github.run_number }}
          EOF